# Path to the data files *.CSV
# Data_filename_day: data/NASDAQ:GOOG_day_[2015-12-17][2025-12-17]_insightsentry.CSV
Data_filename_day: data/NASDAQ:GOOG_day_[2015-12-17][2025-12-17]_FMP.CSV

# size type: 'value' 'amount' 'percent'
Trade:
  size: 1
  size_type: amount

# Start cash value
Initial_cash: 10000

Days: 2